[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mercury"
authors = [{name = "Trent Fellbootman", email = "trentfellbootman@gmail.com"}]
dynamic = ["version", "description"]