CONDENSED_TAGS_NAMESPACE_DELIMITER = '::'
CONDENSED_TAGS_CONCATENATION_DELIMITER = '.'
CONDENSED_TAGS_IGNORED_CHARS = {' ', '\n', '\n\r', '\r\n'}
CONDENSED_TAGS_NESTED_FIELD_DELIMITER_START = '{'
CONDENSED_TAGS_NESTED_FIELD_DELIMITER_END = '}'
CONDENSED_TAGS_PARALLEL_SEPARATOR = ','
TAG_COMPONENT_NAME_REGULAR_EXPRESSION = r'^([a-zA-Z0-9_-]+)$'

UNFILLED_VALUE_PLACEHOLDER = 'unfilled'

BOOLEAN_TRUE_VALUES = {'true', '1', 'True', 'TRUE'}
BOOLEAN_FALSE_VALUES = {'false', '0', 'False', 'FALSE'}

BENCHMARK_TAG_PREFIX = 'benchmark::'
