CONDENSED_TAGS_NAMESPACE_DELIMITER = '::'
CONDENSED_TAGS_CONCATENATION_DELIMITER = '.'
CONDENSED_TAGS_IGNORED_CHARS = {' ', '\n', '\n\r', '\r\n'}
CONDENSED_TAGS_NESTED_FIELD_DELIMITER_START = '{'
CONDENSED_TAGS_NESTED_FIELD_DELIMITER_END = '}'
CONDENSED_TAGS_PARALLEL_SEPARATOR = ','
TAG_COMPONENT_NAME_RE = r'^([a-zA-Z0-9_-]+)$'